#!/bin/bash

./createLivre

cd $1

clear

cat page1.txt

NBPAGE=1

while [ $NBPAGE -ne 11 ] && [ $NBPAGE -ne 14 ] && [ $NBPAGE -ne 4 ] && [ $NBPAGE -ne 10 ] && [ $NBPAGE -ne 6 ] && [ $NBPAGE -ne 15 ]
do
	
	read CHOIX

	if [ $CHOIX -eq $(($NBPAGE*2)) ] || [ $CHOIX -eq $(($NBPAGE*2+1)) ]
	then
		clear
		cat page$CHOIX.txt
		
	else
		echo "Les codes de cheats ne sont pas autorisés"
		break;
		
	fi
	NBPAGE=$CHOIX

done


if [ $NBPAGE -eq 11 ] || [ $NBPAGE -eq 14 ]
then
	cat page16.txt
else
	echo 'Vous avez perdu lamentablement'
fi
